# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='City', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(default='hotel name', max_length=200)),
                ('city_hotel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Hotel')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wishes_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanePlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plane_name', models.CharField(default='plane name', max_length=100)),
                ('airport_name_start', models.CharField(default='airport name', max_length=100)),
                ('airport_name_end', models.CharField(default='airport name', max_length=100)),
                ('end_city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city_name', to='ticketapp.City')),
                ('start_city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city_name', to='ticketapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_number', models.IntegerField(default=1)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('pplan_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.PlanePlan')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(default='buisness/econom', max_length=100)),
                ('price', models.FloatField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.TicketType'),
        ),
        migrations.AddField(
            model_name='planeplan',
            name='terminal_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.TerminalName'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='ticket_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Ticket'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
