# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Звёзды отеля',
            field=models.IntegerField(default=1),
        ),
    ]
