# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_hotel_звёзды отеля'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Звёзды отеля',
            new_name='h_starts',
        ),
    ]
