# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20170528_0049'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderticket',
            name='code',
            field=models.IntegerField(default=1),
        ),
    ]
