# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20170529_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='ticket_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Ticket'),
        ),
    ]
