# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_auto_20170529_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='status',
            field=models.CharField(default='бронь', max_length=50),
        ),
    ]
