# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_orderticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='/Users/sashapekh/projects/diplom/AirLine', upload_to='/Users/sashapekh/projects/diplom/AirLinefiles/hotels_img'),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
