# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20170604_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
