# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_hotel_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='/Users/sashapekh/projects/diplom/AirLine', upload_to='/Users/sashapekh/projects/diplom/AirLine/media/hotels_img'),
        ),
    ]
