# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_auto_20170604_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
