# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_auto_20170604_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/hotels_img/'),
        ),
    ]
