# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0014_auto_20170604_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(default='Обычный', max_length=100)),
                ('max_capacity', models.IntegerField(default=1, max_length=100)),
                ('food', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='day_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='hotel_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Hotel'),
        ),
    ]
