# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0018_auto_20170606_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhotel',
            name='reservation_room_fk',
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='food_delivery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='person_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='room_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='room_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhotel',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
